database:
    # password is secretdatabasepassword
    password: rMetQt2NUhq0WBvD1J9HZYGnK+OwjDmdmToPraVuV0zzCymY/YKoMJHnqiyoV6PvLctri/NLZx97JCwEV6z9miT+B2WGS1as3POQCYmlfXEC6Zgt5Gs37yyUhtSTsaVHk1m6IIPoATndVZPX7zc+H1KqEu+4Cnr+bFl0PTTJz8ZuMG7aMk4e2iFMEgCYY6LcwD/2U563dsgykyTju59fdUJUVJaCa69YQHo+dTXMa+h9FA3RZxOtHl7dCsaKmU6cdbHUbuISlwO/SdcAFlpGDLLSrG0uAzt7/S8SZOJQ4CP/0BnFeX4LUceK/zqDU/0SPM2Jn8/rhtXdlwwlCw1bWw==
